name: replace-appsetting

#on:
#  release:
#    types: [created]

on:
 workflow_dispatch:
#   inputs:
#     version:
#       required: true
#       description: バージョン
#       default: v1.0.0
       
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      #カレントディレクトリ表示（検証用）
      - name: Current-dir-disp
        run: |
          pwd

      #カレントディレクトリの中のファイル、フォルダを表示（検証用）
      - name: Current-dir-sub-disp1
        run: |
          ls

      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Setup Gradle
        #uses: gradle/gradle-build-action@v3
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      #カレントディレクトリの中のファイル、フォルダを表示（検証用）
      - name: Current-dir-sub-disp2
        run: |
          ls
          
      #gradlewに権限追加
      - name: Grant execute permission for gradlew
        working-directory: publicbatchapp
        run: chmod +x gradlew

      #appsettings.ymlの更新前中身表示
      - name: before-appsettings.yml
        run: |
          cat publicbatchapp/src/main/resources/appsettings.yml
          
      # ここで設定ファイルを書き換える
      - name: replace appsettings.yml
        uses: microsoft/variable-substitution@v1
        with:
          files: 'publicbatchapp/src/main/resources/appsettings.yml'
        env:
          spring.datasource.url: "ReplaceUrl"
          #VAR2: 'value2'
          #SECRET: ${{ secrets.MY_SECRET }}

      #appsettings.ymlの更新後中身表示
      - name: after-appsettings.yml
        run: |
          cat publicbatchapp/src/main/resources/appsettings.yml
          
      # build
      - name: Build with Gradle
        working-directory: ./publicbatchapp
        run: ./gradlew build
  
